#!/bin/bash

# Helper script to add new files to Xcode project
# This provides the file paths that need to be manually added

echo "========================================"
echo "Files to Add to Xcode Project"
echo "========================================"
echo ""
echo "Please add these files manually in Xcode:"
echo ""
echo "1. Supporting Files/Config.plist"
echo "   Full path: $(pwd)/realtime-caltrain/Supporting Files/Config.plist"
echo ""
echo "2. Models/API/GTFSRealtimeModels.swift"
echo "   Full path: $(pwd)/realtime-caltrain/Models/API/GTFSRealtimeModels.swift"
echo ""
echo "3. Services/CaltrainAPIClient.swift"
echo "   Full path: $(pwd)/realtime-caltrain/Services/CaltrainAPIClient.swift"
echo ""
echo "========================================"
echo "Instructions:"
echo "========================================"
echo ""
echo "1. Open realtime-caltrain.xcodeproj in Xcode"
echo "2. Right-click on 'realtime-caltrain' folder in project navigator"
echo "3. Select 'Add Files to realtime-caltrain...'"
echo "4. Navigate to and select each file above"
echo "5. UNCHECK 'Copy items if needed'"
echo "6. Select 'Create groups' (not folder references)"
echo "7. Ensure target 'realtime-caltrain' is checked"
echo "8. Click Add"
echo ""
echo "Or simply drag and drop the files from Finder into Xcode!"
echo ""
echo "========================================"
echo "API Key Configuration"
echo "========================================"
echo ""
echo "After adding files, configure your API key:"
echo ""
echo "1. Get API key from: https://511.org/open-data/token"
echo "2. Open Config.plist in Xcode"
echo "3. Replace 'YOUR_511_API_KEY_HERE' with your actual key"
echo ""
echo "========================================"
echo "Schema Migration (Required)"
echo "========================================"
echo ""
echo "The CaltrainStation model changed. Reset simulator:"
echo ""
echo "  xcrun simctl erase all"
echo ""
echo "Or delete the app from simulator manually."
echo ""
echo "========================================"

# Optionally try to open Xcode
if [ "$1" = "--open" ]; then
    echo "Opening Xcode project..."
    open realtime-caltrain.xcodeproj
fi
