# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

SCREENSHOT_DEVICES = [
  "iPhone 11 Pro Max",          # 6.5"
  "iPad Pro 13-inch (M5)",      # 13"
]

platform :ios do
  desc "Generate screenshots"
  lane :screenshots do
    # Clear previous screenshots before starting
    sh("rm -rf './fastlane/screenshots/en-US'")

    # Run each device sequentially: boot, grant permissions, capture, then move on
    SCREENSHOT_DEVICES.each do |device|
      sh("xcrun simctl boot '#{device}' || true")
      sh("sleep 3")
      sh("xcrun simctl privacy '#{device}' grant location net.fewald.caltrain")
      # Set location to San Francisco Caltrain Station as backup
      # Primary location is set via XCUIDevice.shared.location in the test itself
      sh("xcrun simctl location '#{device}' set '37.7762,-122.3947'")
      sh("sleep 2")

      capture_screenshots(
        stop_after_first_error: false,
        number_of_retries: 1,
        scheme: "caltrain",
        configuration: "Release",
        xcargs: "ENABLE_TESTABILITY=YES -disable-concurrent-testing",
        only_testing: [
            "caltrainUITests/Screenshot/testScreenshots",
        ],
        devices: [device],
        erase_simulator: false,
        skip_open_summary: true,
        clear_previous_screenshots: false
      )
    end
  end
end
